import os
import re
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
IMPORT_PATTERN = re.compile(r"from\s+['\"]@/([^'\"]+)['\"]")
FILE_SUFFIXES = (".ts", ".tsx", ".js", ".jsx")

modules = defaultdict(set)

for dirpath, _, filenames in os.walk(ROOT):
    for filename in filenames:
        if not filename.endswith(FILE_SUFFIXES):
            continue
        full_path = os.path.join(dirpath, filename)
        rel_path = os.path.relpath(full_path, ROOT)

        with open(full_path, 'r', encoding='utf-8') as file:
            for line in file:
                match = IMPORT_PATTERN.search(line)
                if match:
                    module = match.group(1)
                    modules[module].add(rel_path)

print('# Supafund Import Mapping')
print('# Generated by scripts/list_dependencies.py\n')

for module in sorted(modules):
    print(f'- {module}')
    for rel_path in sorted(modules[module]):
        print(f'  - {rel_path}')
    print()
