apiVersion: v1
stringData:
    ethereum_private_key.txt: '0xbdcc7e0f41182e36ff9d535b7fa25e40bf9fd38f992d21607e8b50b33888d99d'
kind: Secret
metadata:
  annotations: {}
  name: agent-validator-0-key
type: Opaque
