apiVersion: v1
stringData:
    ethereum_private_key.txt: '0x7c7ea8b2f666fb8e202cc5c3aff741a4c416fa372acd2ad6c2a53f7f86aab1ca'
kind: Secret
metadata:
  annotations: {}
  name: agent-validator-0-key
type: Opaque
