version: '2.4'
services:
  trader9sEY_tm_0:
    user: '1000'
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 0.5
    container_name: trader9sEY_tm_0
    hostname: trader9sEY_tm_0
    image: valory/open-autonomy-tendermint:0.20.2
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
    - ID=0
    - PROXY_APP=tcp://trader9sEY_abci_0:26658
    - TMHOME=/tendermint/node0
    - CREATE_EMPTY_BLOCKS=true
    - DEV_MODE=0
    - LOG_FILE=/logs/node_0.txt
    - LOG_LEVEL=INFO
    - WRITE_TO_LOG=false
    working_dir: /tendermint
    command:
    - run
    - --no-reload
    - --host=0.0.0.0
    - --port=8080
    depends_on:
      trader9sEY_abci_0:
        condition: service_healthy
    networks:
      service_trader9sEY_localnet:
        ipv4_address: 192.167.11.3
    volumes:
    - ./nodes:/tendermint:Z
    - ./persistent_data/logs:/logs:Z
  trader9sEY_abci_0:
    mem_reservation: 256M
    mem_limit: 1024M
    cpus: 1.0
    container_name: trader9sEY_abci_0
    image: supafund/oar-trader:bafybeicxhkpr3ro7osdhatltc2fo2df534o6y2mwkargi6a2vni4rwaqs4
    env_file: agent_0.env
    user: '501:20'
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      service_trader9sEY_localnet:
        ipv4_address: 192.167.11.2
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - ./persistent_data/logs:/logs:Z
    - ./agent_keys/agent_0:/agent_key:Z
    - ../persistent_data:/data:Z
    - ../benchmarks:/Users/andydeng/Downloads/supafund-agent/supafund-agent/quickstart/.operate/services/sc-0abbe0aa-e995-4a35-ae9b-05ac89af917a/benchmarks:Z
    ports:
    - 8716:8716
networks:
  service_trader9sEY_localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.167.11.0/24
